### PR TITLE
1.20.3 and fixes

### LINKED ISSUE #8: [Feature Request] 1.20.4 Support
HealthHider 1.0.4 does not support Minecraft 1.20.4

### PR DESCRIPTION
**Pull request by MrKinau**
This PR attempts to:
1. update to 1.20.3
2. fixes an issue, where my client log got spammed with the following error message
```
[09:08:01] [Render thread/ERROR]: Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.0.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Invalid entity data item type for field 15 on entity class_1613['Skeleton'/266, l='ClientLevel', x=64.51, y=13.00, z=-34.69]: old=0(class java.lang.Byte), new=0.0(class java.lang.Float)
	at net.minecraft.class_2945.method_12785(class_2945.java:204) ~[client-intermediary.jar:?]
	at net.minecraft.class_2945.method_12779(class_2945.java:191) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11093(class_634.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11808(class_2739.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_11054(class_2739.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_48294(class_634.java:2182) ~[client-intermediary.jar:?]
	at net.minecraft.class_8042.method_48329(class_8042.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_8042.method_11054(class_8042.java:6) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 13 more
```
3. add folia support

(closes #8)

### CODE REVIEW

**Comment by NoahvdAa** [comment]
Thanks! Looks good from web, will test soon™️

**Comment by Potothingi** [comment]
My build issue?
```
[14:08:29 INFO]: [HealthHider] Enabling HealthHider v1.0.4
[14:08:29 ERROR]: Error occurred while enabling HealthHider v1.0.4 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/resources/ResourceLocation
        at me.noahvdaa.healthhider.HealthHider.loadConfig(HealthHider.java:53) ~[HealthHider-1.0.4-dev-all.jar:?]
        at me.noahvdaa.healthhider.HealthHider.onEnable(HealthHider.java:27) ~[HealthHider-1.0.4-dev-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-328]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-328]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.20.4.jar:git-Paper-328]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:552) ~[paper-1.20.4.jar:git-Paper-328]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-328]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-328]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-328]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.resources.ResourceLocation
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 12 more
[14:08:29 INFO]: [HealthHider] Disabling HealthHider v1.0.4
```

**Comment by MrKinau** [comment]
looks like you're testing with the mojmap version `*-dev-all.jar` on an obfuscated server. Either test the normal obfuscated jar (without suffix) on this server or test the `*dev-all.jar` on a mojmap server. Maybe it's something completely different, but that's just my guess, as it works for me the normal way with the no-suffix jar without this error (only after mixing the mappings, I'll get such error)

**Comment by Potothingi** [comment]
Yes, that's my problem. It works now.

**Review by NoahvdAa — APPROVED** [review]

**Comment by NoahvdAa** [comment]
Managed to break something with GitHub's stupid CLI tool and it's not letting me push to your master branch now...
Manually merged in https://github.com/NoahvdAa/HealthHider/commit/6ca04eb7158ca906dcc7fc3b3e907399eb709a95 (your commits stil exist as separate commits, no worries :P).

Thanks for contributing!

**Pull request closed without merging**
